export { default as noPhoto } from './no-photo.jpg'

export { default as kabanov_leonid } from './no_party/kabanov_leonid.jpg'
export { default as bazhenov } from './no_party/bazhenov.jpg'
export { default as gulin } from './no_party/gulin.jpg'
export { default as losev } from './no_party/losev.jpg'
export { default as kurpek } from './no_party/kurpek.jpg'
export { default as podles } from './no_party/podles.jpg'
export { default as rodionov } from './no_party/rodionov.jpg'
export { default as yanchich } from './no_party/yanchich.jpg'
export { default as borodin } from './no_party/borodin.jpg'
export { default as kornienko } from './no_party/kornienko.jpg'
export { default as sokolovA } from './no_party/sokolov.jpg'
export { default as chraplak } from './no_party/chraplak.jpg'
export { default as nikolaev } from './no_party/nikolaev.jpg'
export { default as karpov } from './no_party/karpov.jpg'
export { default as krivonosov } from './no_party/krivonosov.jpg'
export { default as panovEgor } from './no_party/panov_egor.jpg'
export { default as aleksanyan_nelli } from './no_party/aleksanyan_nelli.jpg'
export { default as ivleva_svetlana } from './no_party/ivleva_svetlana.jpg'
export { default as tunyaeva_natalia } from './no_party/tunyaeva_natalia.jpg'
export { default as georgievskiy } from './no_party/georgievskiy.jpg'
export { default as kudryavzeva } from './no_party/kudryavzeva.jpg'
export { default as palutin } from './no_party/palutin.jpg'
export { default as ratushniy } from './no_party/ratushniy.jpg'
export { default as vorobiev } from './no_party/vorobiev.jpg'

export { default as pyrinov } from './yabloko/pyrinov.jpg'
export { default as strelnikov } from './yabloko/strelnikov.jpg'
export { default as beylin } from './yabloko/beylin.jpg'
export { default as mushtenko_sergey } from './yabloko/mushtenko_sergey.jpg'
export { default as bobrov_aleksandr } from './yabloko/bobrov_aleksandr.jpg'
export { default as evsukov_ilya } from './yabloko/evsukov_ilya.jpg'

export { default as solomatina_elena } from './er/solomatina_elena.jpg'
export { default as avdeev_sergey } from './er/avdeev_sergey.jpg'
export { default as rusakov_vladimir } from './er/rusakov_vladimir.jpg'
export { default as chufinev_aleksandr } from './er/chufinev_aleksandr.jpg'
export { default as boiko_andrei } from './er/boiko_andrei.jpg'
export { default as shvezov_dmitriy } from './er/shvezov_dmitriy.jpg'
export { default as tatarinzev_sergey } from './er/tatarinzev_sergey.jpg'

export { default as altukhova_yuliya } from './new_people/altukhova_yuliya.jpg'
export { default as anferov } from './new_people/anferov.jpg'
export { default as bespalova_diana } from './new_people/bespalova_diana.jpg'
export { default as ekaterina_baklanova } from './new_people/ekaterina_baklanova.jpg'
export { default as gurchenko_sergey } from './new_people/gurchenko_sergey.jpg'
export { default as gurskaya } from './new_people/gurskaya.jpg'
export { default as ivanov_dmitriy } from './new_people/ivanov_dmitriy.jpg'
export { default as karygin } from './new_people/karygin.jpg'
export { default as kovaleva_elena } from './new_people/kovaleva_elena.jpg'
export { default as malkova_olga } from './new_people/malkova_olga.jpg'
export { default as penkova_kseniya } from './new_people/penkova_kseniya.jpg'
export { default as rogozin_maksim } from './new_people/rogozin_maksim.jpg'
export { default as stepakov_maksim } from './new_people/stepakov_maksim.jpg'
export { default as strelnikov_andrey } from './new_people/strelnikov_andrey.jpg'
export { default as tukhin_vladimir } from './new_people/tukhin_vladimir.jpg'
export { default as zhavoronkova_yuliya } from './new_people/zhavoronkova_yuliya.jpg'
export { default as zuev } from './new_people/zuev.jpg'
export { default as zykeev } from './new_people/zykeev.jpg'

export { default as hatunzev_stanislav } from './rodina/hatunzev_stanislav.jpg'
export { default as ryabykh_aleksandr } from './rodina/ryabykh_aleksandr.jpg'
export { default as semin_gennadiy } from './rodina/semin_gennadiy.jpg'
export { default as batishev_eduard } from './rodina/batishev_eduard.jpg'
export { default as zakharov_aleksandr } from './rodina/zakharov_aleksandr.jpg'
export { default as grachev_konstantin } from './rodina/grachev_konstantin.jpg'
export { default as krasikov_aleksandr } from './rodina/krasikov_aleksandr.jpg'
export { default as petukhov_maksim } from './rodina/petukhov_maksim.jpg'
export { default as ivanishev_vitaliy } from './rodina/ivanishev_vitaliy.jpg'
export { default as filatov_andrey } from './rodina/filatov_andrey.jpg'
export { default as kucherin_pavel } from './rodina/kucherin_pavel.jpg'
export { default as shvidkiy_vladimir } from './rodina/shvidkiy_vladimir.jpg'
export { default as ofizerova_olga } from './rodina/ofizerova_olga.jpg'
export { default as ivanov_anton } from './rodina/ivanov_anton.jpg'
export { default as kudinova_tatiana } from './rodina/kudinova_tatiana.jpg'
export { default as andreev_nikolay } from './rodina/andreev_nikolay.jpg'
export { default as chekmarev_artem } from './rodina/chekmarev_artem.jpg'
export { default as ostroushko_ivan } from './rodina/ostroushko_ivan.jpg'
export { default as yakovez_elena } from './rodina/yakovez_elena.jpg'
export { default as shalygin_nikolay } from './rodina/shalygin_nikolay.jpg'
export { default as safonov_sergey } from './rodina/safonov_sergey.jpg'
export { default as sokolov_vyacheslav } from './rodina/sokolov_vyacheslav.jpg'
export { default as shulekina_nataliya } from './rodina/shulekina_nataliya.jpg'
export { default as borisov_igor } from './rodina/borisov_igor.jpg'
export { default as cherednikov_vladimir } from './rodina/cherednikov_vladimir.jpg'
export { default as dolbnya_gennadiy } from './rodina/dolbnya_gennadiy.jpg'
export { default as gushin_roman } from './rodina/gushin_roman.jpg'
export { default as kopachev_gennadiy } from './rodina/kopachev_gennadiy.jpg'
export { default as krukov_alexey } from './rodina/krukov_alexey.jpg'
export { default as malzev_yuriy } from './rodina/malzev_yuriy.jpg'
export { default as masloboev_sergey } from './rodina/masloboev_sergey.jpg'
export { default as osinin_kirill } from './rodina/osinin_kirill.jpg'
export { default as polnikov_igor } from './rodina/polnikov_igor.jpg'
export { default as polunin_artem } from './rodina/polunin_artem.jpg'
export { default as ponomarev_aleksandr } from './rodina/ponomarev_aleksandr.jpg'
export { default as rosnovskaya_svetlana } from './rodina/rosnovskaya_svetlana.jpg'
export { default as skrinnikov_boris } from './rodina/skrinnikov_boris.jpg'
export { default as sokolov_viktor } from './rodina/sokolov_viktor.jpg'
export { default as suprunov_vladimir } from './rodina/suprunov_vladimir.jpg'
export { default as vladimirov_vyacheslav } from './rodina/vladimirov_vyacheslav.jpg'
export { default as volkov_andrey } from './rodina/volkov_andrey.jpg'

export { default as titaev_sergey } from './sr/titaev_sergey.jpg'
export { default as kolyagin } from './sr/kolyagin.jpg'
export { default as maslennikova } from './sr/maslennikova.jpg'
export { default as peshkov } from './sr/peshkov.jpg'
export { default as petrov } from './sr/petrov.jpg'
export { default as rymar } from './sr/rymar.jpg'
export { default as slepchenko } from './sr/slepchenko.jpg'
export { default as zheltukha } from './sr/zheltukha.jpg'

export { default as kovalev_vasiliy } from './kprf/kovalev_vasiliy.jpg'
export { default as korchagin } from './kprf/korchagin.jpg'
export { default as pomeranzev } from './kprf/pomeranzev.jpg'
export { default as roslik } from './kprf/roslik.jpg'
export { default as sivoplyasov } from './kprf/sivoplyasov.jpg'
export { default as emelyanov_evgeniy } from './emelyanov_evgeniy.jpg'

// область
// export { default as ivanov_svyatoslav } from './rodina/ivanov_svyatoslav.jpg'
// export { default as kovalev_artur } from './rodina/kovalev_artur.jpg'
// export { default as radinovich_lubomir } from './rodina/radinovich_lubomir.jpg'
// export { default as semenov_maksim } from './rodina/semenov_maksim.jpg'
